services:
  garbin-souf-api:
    image: garbin-souf-api
    build: ./
    ports:
      - 5005:5005
    volumes:
      - ./src:/app/src
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
